services:
  application:
    build: .
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/teste
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_DATASOURCE_USER: postgres

  db:
    image: postgres:latest
    ports:
      - "5431:5432"
    volumes:
      - "postgres-volume:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: teste
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
volumes:
  postgres-volume:
